### PR TITLE
Add 7.62mm / 300mil horizontal resistor.

### PR DESCRIPTION
**Pull request by DavidGriffith**
A 1/4W resistor is just under 7.62mm / 300mil long.  This 7.62mm resistor footprint perfect for matching a 100mil grid and when a 10mm footprint would take up too much space.

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi David,

Please review rules 6.3 and 6.6. If you would like to fix some other
resistors at the same time that would be great. If you need further
explanation about the rules, let me know.

Thanks!

**Comment by DavidGriffith** [comment]
How's this?  If this is okay, I'll go ahead and fix some other resistors accordingly.

**Comment by CarlPoirier** [comment]
Rule 6.6 is about courtyard clearance, not pad clearance. Please have a look at some examples in the Resistors_SMD.pretty library. The courtyard is that grey rectangle all over it.

I just clarified that rule 6.6 and split it over 6.6 and 6.7. I hope this makes it more clear.

Carl

**Comment by DavidGriffith** [comment]
Now I understand.  Here's a courtyard.  I'm not sure if "...position is rounded on a grid of 0.05mm" means that lines must start and stop on 0.05mm points.  I don't think it's possible to do that and have the footprint remain symmetrical.

**Comment by CarlPoirier** [comment]
Here I did the first one for you. You will see the courtyard clearance of 0.25mm with both the silkscreen and the pads, rounded to the nearest 0.05mm. It doesn't matter if it is not symmetrical. I pasted the .kicad_mod file content here so you will be able to commit it in your name.

(module a:Resistor_Horizontal_RM7.62mm (layer F.Cu) (tedit 54BFB939)
  (descr "Resistor, Axial,  RM 7.62mm, 1/4W,")
  (tags "Resistor, Axial, RM 7.62mm, 1/4W,")
  (fp_text reference Resistor_Horizontal_RM7.62mm (at 4 -3.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value VAL** (at 7.62 3.81) (layer F.SilkS) hide
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start 8.55 1.33) (end 8.55 -1.33) (layer F.CrtYd) (width 0.05))
  (fp_line (start -0.95 1.33) (end 8.55 1.33) (layer F.CrtYd) (width 0.05))
  (fp_line (start -0.95 -1.33) (end 8.55 -1.33) (layer F.CrtYd) (width 0.05))
  (fp_line (start -0.95 -1.33) (end -0.95 1.33) (layer F.CrtYd) (width 0.05))
  (fp_line (start 2 -1) (end 2 1) (layer F.SilkS) (width 0.15))
  (fp_line (start 5.62 1) (end 2 1) (layer F.SilkS) (width 0.15))
  (fp_line (start 2 -1) (end 5.62 -1) (layer F.SilkS) (width 0.15))
  (fp_line (start 5.62 -1) (end 5.62 1) (layer F.SilkS) (width 0.15))
  (fp_line (start 6.62 0) (end 5.62 0) (layer F.SilkS) (width 0.15))
  (fp_line (start 1 0) (end 2 0) (layer F.SilkS) (width 0.15))
  (pad 1 thru_hole circle (at 0 0) (size 1.397 1.397) (drill 0.8128) (layers *.Cu *.SilkS *.Mask))
  (pad 2 thru_hole circle (at 7.62 0) (size 1.397 1.397) (drill 0.8128) (layers *.Cu *.SilkS *.Mask)
    (clearance 0.25))
  (model Resistors_ThroughHole/Resistor_Horizontal_RM10mm.wrl
    (at (xyz 0 0 0))
    (scale (xyz 0.4 0.4 0.4))
    (rotate (xyz 0 0 0))
  )
)

I hope this helps!

**Pull request closed without merging**
