### PR TITLE
added SIP R-Networks SPI4...7

### PR DESCRIPTION
**Pull request by jkriege2**

### CODE REVIEW

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: Resistor_Array_SIP4
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
checking module: Resistor_Array_SIP5
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
checking module: Resistor_Array_SIP6
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
checking module: Resistor_Array_SIP7
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.05mm.
    No courtyard line found in the module
```

**Comment by jkriege2** [comment]
issues should be fixed ;-)

**Comment by pointhi** [comment]
thanks,

I suggest to heed the 0.25 distance for courtjard and not simply adding some more. When the original footprints are wrong, simply fix them instead of using the wrong dimensions.

It would be cool if you add F.Fab to the other Resistor arrays as well and adjust the silkscreen accordingly. Furthermore, the Silkscreen should be removed from the Pads.

the rest looks fine to me

**Comment by jkriege2** [comment]
OK, I redid all the packages and also added packages for voltage divider and parallel resistor arrays
see C- and B-type in http://cdn-reichelt.de/documents/datenblatt/B400/SIL_WID.pdf

**Comment by jkriege2** [comment]
I'm thinking about redoing the SIP 3D packages. Here's how a new one ( would look, compared to a (slightly shorter) old one:

sip_new
sip_old

**Comment by Schlumpf** [comment]
I like the new 3D Model, but I'm not a librarian, so my opinion doesn't count ;)

**Comment by pointhi** [comment]
I also like the library, but at the current state we don't add scripts into the .pretty repositories.

Does it make sense to have different footprints for ArrayDivider, ...? It looks for me they are the same

**Comment by jkriege2** [comment]
Hhmmm .. I was thinking about this too ... initially I wanted to simply make a series of SIL packages ... then I interpreted the datasheet in a way that there may be different height for different topology types, but looking into more datasheets, they all seem to have the same hieght ;-) ... So I'll change the lib accordingly ... Any KLC  issues, as you added that tag? Or do you mean the script?

cu
JAN

PS: I'll commit the changed lib later (or during the weekend).

**Comment by pointhi** [comment]
No KLC issues, from what I know. I thought about the python script and the multiple footprints when setting the tag.

**Comment by jkriege2** [comment]
OK; I updated the footprints and the 3D packages in a separate PR:
https://github.com/KiCad/kicad-library/pull/740

We have now SIP4...SIP14 and the number references the pin-count, not the resistor count as before!

Ready to pull? Anything missing?

res14

**Comment by jkriege2** [comment]
I created a PR for the creator-script: https://github.com/pointhi/kicad-footprint-generator/pull/12

**Comment by pointhi** [comment]
hm, one last thing which should be fixed:

* http://www.bourns.com/docs/Product-Datasheets/4600x.pdf
* http://www.ctscorp.com/wp-content/uploads/2015/11/770.pdf

The width shown on F.Fab and the Silkscreen is way too small (0.5mm vs 2.5mm). When you change this you could also increase the copper area of the pads so they are easier to solder.

Also please add a SIP4 version

the rest looks fine

**Comment by pointhi** [comment]
thanks, great work!

**Pull request merged**
